steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg=VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - '--build-arg=VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg=VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}'
      - '--build-arg=VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg=VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg=VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/uea-app:${BUILD_ID}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/uea-app:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/uea-app:${BUILD_ID}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/uea-app:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'uea-app'
      - '--image=gcr.io/$PROJECT_ID/uea-app:${BUILD_ID}'
      - '--region=us-east1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--env-vars-file=env.yaml'

images:
  - 'gcr.io/$PROJECT_ID/uea-app:${BUILD_ID}'
  - 'gcr.io/$PROJECT_ID/uea-app:latest'

substitutions:
  _VITE_FIREBASE_API_KEY: 'AIzaSyBCf9jPxD3xCJ0vzHRZe2uCA6ThYpEiQCA'
  _VITE_FIREBASE_AUTH_DOMAIN: 'uea-app-470816.firebaseapp.com'
  _VITE_FIREBASE_PROJECT_ID: 'uea-app-470816'
  _VITE_FIREBASE_STORAGE_BUCKET: 'uea-app-470816.firebasestorage.app'
  _VITE_FIREBASE_MESSAGING_SENDER_ID: '1099351236154'
  _VITE_FIREBASE_APP_ID: '1:1099351236154:web:1b581b8a61769f7d93df03'

options:
  logging: CLOUD_LOGGING_ONLY
